version: "3.8"


services:
  database:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=botdb
    volumes:
       - postgres_data:/data/postgres
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 60s
      timeout: 5s
      retries: 20

  # create tables in database
  migrate:
    image: ghcr.io/muskelo/translator_bot:latest
    command: "/app/migrate"
    environment:
      - DB_CONNSTR=postgresql://postgres:dbpassword@database:5432/botdb?sslmode=disable
    depends_on:
      database:
        condition: service_healthy

  # free translation API
  libretranslate:
    image: libretranslate/libretranslate:v1.3.10
    restart: unless-stopped
    # can be launched for a long time (~30 min)
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 300s
      timeout: 20s
      retries: 100

  bot:
    image: ghcr.io/muskelo/translator_bot:latest
    environment:
      - DB_CONNSTR=postgresql://postgres:dbpassword@database:5432/botdb?sslmode=disable
      - BOT_TOKEN=telegram_bot_token
      - LIBRETRANSLATE_URL=http://libretranslate:5000/
      - DEFAULT_SECONDARY_LANG=en
      - DEFAULT_PRIMARY_LANG=ru
    restart: unless-stopped
    depends_on:
      libretranslate:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  postgres_data:
