name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Docker Login 
        uses: docker/login-action@v2.1.0
        with:
            # Server address of Docker registry. If not set then will default to Docker Hub
            registry: ghcr.io
            # Username used to log against the Docker registry
            username: ${{ github.actor }}
            # Password or personal access token used to log against the Docker registry
            password: ${{ secrets.ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.actor }}/translator_bot:latest
